
name: Test

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/ci.yml"

jobs:
  test:
    name: Test Scalastyle download
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10

    - name: Download Scalastyle
      uses: ./
